[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tcod = "0.15"
tcod = { git = "https://github.com/tomassedovic/tcod-rs.git", rev = "d4ad074"}
rand = "0.3.9"